### ISSUE TITLE
Unexpected lifetime?

### ISSUE THREAD

**Issue by dblanovschi** [Mcat12/intellij-lalrpop#2]
After rebuilding the last version, this is what happened:
(This was taken from [chapter 5.3 of the lalrpop book](http://lalrpop.github.io/lalrpop/lexer_tutorial/003_token_references.html#the-parser))

![image](https://user-images.githubusercontent.com/39565527/91842123-1b74b080-ec5c-11ea-902a-0cf5d80927e3.png)

**Comment by dblanovschi** [comment]
I tried to fix this myself in [`60ec21c`](https://github.com/dblanovschi/intellij-lalrpop/commit/60ec21c3b01a81ce31a524e298bc2990f5138e02). Should I open a PR?

**Comment by Mcat12** [comment]
Thanks for catching this issue and working on a fix! I found a simpler fix in https://github.com/Mcat12/intellij-lalrpop/commit/ae1d42212be44b8ff6ad4fbb227c7e93c95232da, but I appreciate your help.

**Comment by Mcat12** [comment]
Turns out the above change doesn't support characters which use escape sequences, but we can actually remove character parsing altogether because it's only usage is in an unused grammar item, patterns. Patterns may not need to be supported (only used in `extern` blocks, and even then I haven't seen any code which uses it), so I removed them for now.

It it turns out that we need to parse character literals, your changes will probably come in handy!
