### ISSUE TITLE
Cannot correctly parse an enum of an extern lexer.

### ISSUE THREAD

**Issue by dblanovschi** [Mcat12/intellij-lalrpop#4]
I have some code that looks like this:

```rust
extern {
    enum lexer::Tok {
        "+=" => lexer::Tok::AddEq(<TokLoc>),
        "-=" => lexer::Tok::SubEq(<TokLoc>),
        "*=" => lexer::Tok::MulEq(<TokLoc>),
        "/=" => lexer::Tok::DivEq(<TokLoc>),
        "%=" => lexer::Tok::ModEq(<TokLoc>),
        "=" => lexer::Tok::Eq(<TokLoc>),
        // and so on
    }
}
```

The error that I get is at the `lexer::Tok::AddEq(<TokLoc>)` saying `LALRPOP.COMMA or LALRPOP.RBRACE expected, got 'lexer::Tok::AddEq(<T...'`

**Comment by Mcat12** [comment]
Turns out when I was converting the [lalrpop grammar](https://github.com/lalrpop/lalrpop/blob/723678f364790b41d66e747d4eb982897c0edce9/lalrpop/src/parser/lrgrammar.lalrpop) to Grammar-Kit, I didn't properly account for this section of the grammar. This is related to #2, because lalrpop invokes a second parser in the first parser, to parse a "pattern":
https://github.com/lalrpop/lalrpop/blob/723678f364790b41d66e747d4eb982897c0edce9/lalrpop/src/parser/lrgrammar.lalrpop#L345-L351

It looks like this "pattern" is just a subset of Rust grammar, so we can probably inject Rust here like we do for the action code, and just replace the odd `<Type>` notation with whatever it's supposed to be.

**Comment by Mcat12** [comment]
Parsing now completes successfully as of https://github.com/Mcat12/intellij-lalrpop/commit/7095024cd6a1ed1280bd4c8667e175dd0f5e1b45.
