### ISSUE TITLE
Support for 2020.3 EAP(203.* builds)?

### ISSUE THREAD

**Issue by dblanovschi** [Mcat12/intellij-lalrpop#5]
The plugin fails to load in the CLion EAP build 203.3645.37, released today.

**Comment by Mcat12** [comment]
Thanks for making this issue! I'll look into when I get a chance.

**Comment by Mcat12** [comment]
https://github.com/Mcat12/intellij-lalrpop/commit/c06b1cacb388909fe964f7392cb3878ee474e646 should fix this. Unrelated, but I did notice that a recent version of the Rust plugin broke name resolution to crate items inside of the injected blocks. There's some other similar issues reported about macro expansion, so that might be the cause.
